<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5szzPYe' shared service.

return $this->privates['.service_locator.5szzPYe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService.php', true],
]);
