<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTqA4qSb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTqA4qSb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTqA4qSb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTqA4qSb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTqA4qSb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TqA4qSb',
    'container.build_id' => '0c8074f3',
    'container.build_time' => 1554046780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTqA4qSb');
