<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKTcE82s\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKTcE82s/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKTcE82s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKTcE82s\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKTcE82s\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KTcE82s',
    'container.build_id' => 'fc4ea3c5',
    'container.build_time' => 1554400061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKTcE82s');
