<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpVD0R9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpVD0R9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpVD0R9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpVD0R9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRpVD0R9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RpVD0R9',
    'container.build_id' => 'ec57eaaf',
    'container.build_time' => 1554309046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpVD0R9');
